name: Deploy API to server

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/deploy-api.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Refresh known_hosts (safe)
        run: |
          mkdir -p ~/.ssh
          # remove any old key for this host (IP or hostname)
          ssh-keygen -R "${{ secrets.SSH_HOST }}" || true
          # add the current host key from the server
          ssh-keyscan -p "${{ secrets.SSH_PORT || '22' }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Rsync server/ → /srv/party-api
        run: |
          rsync -az --delete \
            -e "ssh -p ${{ secrets.SSH_PORT || '22' }}" \
            --exclude=node_modules --exclude='.git' \
            ./server/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/party-api

      - name: Install, build, restart
        run: |
          ssh -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'SSHCMDS'
          set -e
          cd /srv/party-api
          # make sure we use nvm Node v22 for build
          export PATH=/root/.nvm/versions/node/v22.19.0/bin:$PATH
          node -v
          npm -v

          npm ci
          npm run build

          sudo systemctl restart party-api
          sudo systemctl --no-pager status party-api -n 20 || true
          SSHCMDS
